on:
  push:
    branches: "master"
env:
  AMR_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AMR_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AMR_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AMR_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure via Azure CLI
        run: |
          echo "$AZURE_CREDENTIALS" > azure-credentials.json
          az login --service-principal --tenant $ARM_TENANT_ID --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET
          az account set --subscription $ARM_SUBSCRIPTION_ID
      # Install the latest verssion of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      # Initialize a new or existing Terraform working directory
      # Creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
      # Generate an execution plan for Terraform
      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -out tfplan
      # Save plan to artifacts
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: [terraform-plan]

    steps:
      # Checkout the repository to the github Action Runner
      - name: Checkout
        uses: actions/checkout@v3
      # Install the latest verssion of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      # Initialize a new or existing Terraform working directory
      # Creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
      # Download saved plan from artifacts
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
      # Login to Azure via Azure CLI
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
